- rhine-gloss/rhine-gloss.cabal
- rhine/rhine.cabal
> Version bumps

- rhine/rhine.cabal
- rhine/src/FRP/Rhine/ResamplingBuffer/LIFO.hs
> Add LIFO buffers

- rhine/src/FRP/Rhine/Clock/Select.hs
> added scheduleSelectClockAndMain function

- rhine/src/FRP/Rhine/Clock/Realtime/Event.hs
- rhine/src/FRP/Rhine/Clock/Realtime/Stdin.hs
- rhine/src/FRP/Rhine/Clock/Select.hs
as per issue #42 - hope that this is ok!
> refactor schedules that use Monoid to use Semigroup instead

- rhine/src/FRP/Rhine/ResamplingBuffer/FIFO.hs
- rhine/src/FRP/Rhine/ResamplingBuffer/LIFO.hs
As per #53 -> Hope this is ok!
> Add bounded fifo and lifo buffers

- rhine/src/FRP/Rhine/Reactimation/Combinators.hs
> Update haddocks for ||@

- rhine-gloss/rhine-gloss.cabal
https://github.com/commercialhaskell/stackage/issues/3914
> Adjust gloss version bounds

- rhine/rhine.cabal
- rhine/src/FRP/Rhine/ClSF.hs
- rhine/src/FRP/Rhine/ClSF/Random.hs
- rhine/src/FRP/Rhine/ClSF/Random/Util.hs
> Dev rand t

- rhine/src/FRP/Rhine/Type.hs
I was kinda confused by this since there doesn't seem to be a `un-SN` type. But maybe it's correct though, I haven't fully understood this library yet. Oh and thanks for creating this library!
> Fixed typo

- CHEATSHEET.md
- docs/operators.md
I thought doing #128 would be a good exercise so I tried adding a few patterns and operators I have picked up on. I also added in the small table in the beginning of "Rhine: FRP with Type-Level Clocks" to help with the different terms if that's okay. Please correct me if anything here is wrong!
> Improved cheat sheet

- README.md
The FAQ is pretty simple, as I'd rather refer people to the github issues for longer discussion, and @turion 's awesome examples.
Also, I love the dirth of combinators, but there's a learning curve, so I commented the example to be a little more clear.
> Add a FAQ to README, and comment the README's example

- rhine/src/FRP/Rhine/ClSF/Except.hs
> Remove deprecated dunai Empty type

- rhine-gloss/rhine-gloss.cabal
- rhine-gloss/src/FRP/Rhine/Gloss/IO.hs
> Dev gloss sundry improvements

- rhine-bayes/app/Main.hs
- rhine-bayes/src/FRP/Rhine/Bayes.hs
> Add Poisson, Gamma and Bernoulli processes

- rhine-bayes/app/Main.hs
- rhine-bayes/src/FRP/Rhine/Bayes.hs
- rhine/src/FRP/Rhine.hs
> Dev bayes sundry

- rhine-bayes/ChangeLog.md
- rhine-bayes/rhine-bayes.cabal
- rhine-examples/rhine-examples.cabal
- rhine-gloss/ChangeLog.md
- rhine-gloss/rhine-gloss.cabal
- rhine-terminal/ChangeLog.md
- rhine-terminal/rhine-terminal.cabal
- rhine/ChangeLog.md
- rhine/rhine.cabal
> Bumped versions to 1.0, updated changelogs

- rhine-gloss/src/FRP/Rhine/Gloss/IO.hs
I discovered a bug that occurs when using the `GlossEventClock`: The time variable was not correctly updated.
> Fix event clock in Gloss

- .github/workflows/ci.yml
- cabal.9.4.4.project
See https://github.com/haskell-actions/setup
> Update CI & fix cabal caching

- .github/workflows/ci.yml
> Use get tested github action

- automaton/src/Data/Stream.hs
- automaton/src/Data/Stream/Optimized.hs
Fix https://github.com/turion/rhine/pull/316
> Fix liftA2 migration

- flake.nix
- rhine-bayes/app/Main.hs
- rhine-gloss/src/FRP/Rhine/Gloss/IO.hs
- rhine-gloss/src/FRP/Rhine/Gloss/Pure.hs
- rhine/bench/Sum.hs
- rhine/rhine.cabal
- rhine/src/FRP/Rhine.hs
- rhine/src/FRP/Rhine/ResamplingBuffer.hs
> Dev free async

- .github/workflows/ci.yml
- flake.nix
> Dev nix caching

- automaton/automaton.cabal
- rhine/rhine.cabal
See https://github.com/commercialhaskell/stackage/issues/7391#issuecomment-2208847985
> Bump QuickCheck upper bound

- rhine-bayes/README.md
Fixes https://github.com/turion/rhine/issues/255
> Update rhine bayes readme

- flake.nix
> Split overlay in two
